/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import dao.BangDiemDao;
import dao.SinhVienDao;
import helper.DataValidator;
import helper.MessageDialogHelper;
import java.text.DecimalFormat;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.BangDiem;
import model.SinhVien;

/**
 *
 * @author OS
 */
public class GPAManagementPanel extends javax.swing.JPanel {
    private DefaultTableModel tblModel;
    /**
     * Creates new form GPAManagementPanel
     */
    public GPAManagementPanel() {
        initComponents();
        initTable();
        loadDataToTable();
    }
    
    public void initTable(){
        tblModel = new DefaultTableModel();
        String[] row = new String[]{"Mã sinh viên","Họ tên","Điểm Tiếng anh","Điểm Tin học","Điểm GDTC","Điểm trung bình"};
        tblModel.setColumnIdentifiers(row);
        jTable_QLD.setModel(tblModel);
    }
    
    private void loadDataToTable(){
        try {
            List<BangDiem> list = BangDiemDao.findAll();
            tblModel.setRowCount(0);
            for(BangDiem bangDiem : list){
                float tb = (bangDiem.getTiengAnh()+bangDiem.getTinHoc()+bangDiem.getGDTC())/3;
                String st = String.format("%.2f", tb);
                SinhVien sv = SinhVienDao.findByIdStudent(bangDiem.getMaSinhVien());
                tblModel.addRow(new Object[]{
                   bangDiem.getMaSinhVien(),sv.getHoTen(),bangDiem.getTiengAnh(),bangDiem.getTinHoc(),bangDiem.getGDTC(),st
                });
            }
            tblModel.fireTableDataChanged();
        } catch (Exception e) {
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jTextField_MaSinhVien_Search = new javax.swing.JTextField();
        jButton_TimKiem = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_MaSinhVien = new javax.swing.JTextField();
        jTextField_HoTen = new javax.swing.JTextField();
        jTextField_TiengAnh = new javax.swing.JTextField();
        jTextField_TinHoc = new javax.swing.JTextField();
        jTextField_GDTC = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel_TrungBinh = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jButton_NhapMoi = new javax.swing.JButton();
        jButton_Luu = new javax.swing.JButton();
        jButton_CapNhat = new javax.swing.JButton();
        jButton_Xoa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_QLD = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jButton_Loc = new javax.swing.JButton();
        jTextField_SoLuong = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Quản lý điểm");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel2.setText("Mã sinh viên :");

        jTextField_MaSinhVien_Search.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jButton_TimKiem.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jButton_TimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icon/search.png"))); // NOI18N
        jButton_TimKiem.setText("Tìm kiếm");
        jButton_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TimKiemActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel3.setText("Mã sinh viên :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel4.setText("Họ tên :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel5.setText("Tiếng Anh :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel6.setText("Tin học :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel7.setText("GDTC :");

        jTextField_MaSinhVien.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jTextField_MaSinhVien.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_MaSinhVienFocusLost(evt);
            }
        });

        jTextField_HoTen.setEditable(false);
        jTextField_HoTen.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jTextField_HoTen.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jTextField_TiengAnh.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jTextField_TiengAnh.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_TiengAnhFocusLost(evt);
            }
        });

        jTextField_TinHoc.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jTextField_TinHoc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_TinHocFocusLost(evt);
            }
        });

        jTextField_GDTC.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jTextField_GDTC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_GDTCFocusLost(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Điểm TB");

        jLabel_TrungBinh.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_TrungBinh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_TrungBinh.setText("9.5");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel8)
                .addContainerGap(13, Short.MAX_VALUE))
            .addComponent(jLabel_TrungBinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel_TrungBinh)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jButton_NhapMoi.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jButton_NhapMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icon/new.png"))); // NOI18N
        jButton_NhapMoi.setText("Nhập mới");
        jButton_NhapMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NhapMoiActionPerformed(evt);
            }
        });

        jButton_Luu.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jButton_Luu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icon/save.png"))); // NOI18N
        jButton_Luu.setText("Lưu");
        jButton_Luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LuuActionPerformed(evt);
            }
        });

        jButton_CapNhat.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jButton_CapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icon/update.png"))); // NOI18N
        jButton_CapNhat.setText("Cập nhật");
        jButton_CapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CapNhatActionPerformed(evt);
            }
        });

        jButton_Xoa.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jButton_Xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icon/delete.png"))); // NOI18N
        jButton_Xoa.setText("Xóa");
        jButton_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_XoaActionPerformed(evt);
            }
        });

        jTable_QLD.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jTable_QLD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_QLD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_QLDMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_QLD);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel9.setText("Số lượng :");

        jButton_Loc.setBackground(new java.awt.Color(51, 255, 255));
        jButton_Loc.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jButton_Loc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icon/loc.png"))); // NOI18N
        jButton_Loc.setText("Sàng lọc");
        jButton_Loc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LocActionPerformed(evt);
            }
        });

        jTextField_SoLuong.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator1)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(40, 40, 40)
                                        .addComponent(jTextField_MaSinhVien_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel5))
                                                .addGap(33, 33, 33)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTextField_TinHoc)
                                                    .addComponent(jTextField_GDTC)
                                                    .addComponent(jTextField_TiengAnh)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel3)
                                                    .addComponent(jLabel4))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTextField_MaSinhVien)
                                                    .addComponent(jTextField_HoTen))))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(45, 45, 45)
                                                .addComponent(jButton_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jButton_NhapMoi, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jButton_Luu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jButton_CapNhat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton_TimKiem)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_Loc, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_MaSinhVien_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_TimKiem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_NhapMoi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_Luu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_CapNhat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_Xoa)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField_MaSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jTextField_HoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_TiengAnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jTextField_TinHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jTextField_GDTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jButton_Loc)
                    .addComponent(jTextField_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_NhapMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NhapMoiActionPerformed
        jTextField_MaSinhVien.setText("");
        jTextField_HoTen.setText("");
        jTextField_TiengAnh.setText("");
        jTextField_TinHoc.setText("");
        jTextField_GDTC.setText("");
        jTextField_MaSinhVien.setEditable(true);
    }//GEN-LAST:event_jButton_NhapMoiActionPerformed

    private void jButton_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TimKiemActionPerformed
        StringBuilder sb = new StringBuilder();
        DataValidator.validatorEmpty(jTextField_MaSinhVien_Search, sb, "Mã sinh viên không được trống");
        if(sb.length() > 0){
            MessageDialogHelper.showErrorDialog(this, sb.toString(), "Lỗi");
            return ;
        }
        
        try {
            SinhVien sv = SinhVienDao.findByIdStudent(jTextField_MaSinhVien_Search.getText());
            BangDiem bangDiem = BangDiemDao.findById(jTextField_MaSinhVien_Search.getText());
            jTextField_MaSinhVien.setText(bangDiem.getMaSinhVien());
            jTextField_HoTen.setText(sv.getHoTen());
            jTextField_TiengAnh.setText(bangDiem.getTiengAnh()+"");
            jTextField_TinHoc.setText(bangDiem.getTinHoc()+"");
            jTextField_GDTC.setText(bangDiem.getGDTC()+"");
            jTextField_MaSinhVien.setEditable(false);
        } catch (Exception e) {
            MessageDialogHelper.showErrorDialog(getParent(), "Thông tìm thấy thông tin điểm sinh viên", "Thông báo");
        }
    }//GEN-LAST:event_jButton_TimKiemActionPerformed

    private void jTextField_GDTCFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_GDTCFocusLost
        if(jTextField_TiengAnh.getText().equals("") || jTextField_TinHoc.getText().equals("") || jTextField_GDTC.getText().equals("")){
            return ;
        }
        float ta = Float.parseFloat(jTextField_TiengAnh.getText());
        float th = Float.parseFloat(jTextField_TinHoc.getText());
        float tc = Float.parseFloat(jTextField_GDTC.getText());
        
        float tbinh = (ta+th+tc)/3;
        
        String st = String.format("%.2f",tbinh);
        jLabel_TrungBinh.setText(st);
    }//GEN-LAST:event_jTextField_GDTCFocusLost

    private void jButton_LuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LuuActionPerformed
        StringBuilder sb = new StringBuilder();
        DataValidator.validatorEmpty(jTextField_MaSinhVien, sb, "Mã sinh viên không được trống");
        if(sb.length() > 0){
            MessageDialogHelper.showErrorDialog(this, sb.toString(), "Lỗi");
            return ;
        }
        try {
            BangDiem bangDiem = new BangDiem();
            bangDiem.setMaSinhVien(jTextField_MaSinhVien.getText());
            bangDiem.setTiengAnh(Float.parseFloat(jTextField_TiengAnh.getText()));
            bangDiem.setTinHoc(Float.parseFloat(jTextField_TinHoc.getText()));
            bangDiem.setGDTC(Float.parseFloat(jTextField_GDTC.getText()));
            
            if(BangDiemDao.saveBangDiem(bangDiem)){
                MessageDialogHelper.showMessageDialog(this, "Thêm thông tin điểm thành công", "Thông báo");
                loadDataToTable();
            } else {
                MessageDialogHelper.showErrorDialog(this, "Thông điểm không thêm thành công", "Lỗi");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton_LuuActionPerformed

    private void jButton_CapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CapNhatActionPerformed
        StringBuilder sb = new StringBuilder();
        DataValidator.validatorEmpty(jTextField_MaSinhVien, sb, "Mã sinh viên không được trống");
        if(sb.length() > 0){
            MessageDialogHelper.showErrorDialog(this, sb.toString(), "Lỗi");
            return ;
        }
        try {
            BangDiem bangDiem = new BangDiem();
            bangDiem.setMaSinhVien(jTextField_MaSinhVien.getText());
            bangDiem.setTiengAnh(Float.parseFloat(jTextField_TiengAnh.getText()));
            bangDiem.setTinHoc(Float.parseFloat(jTextField_TinHoc.getText()));
            bangDiem.setGDTC(Float.parseFloat(jTextField_GDTC.getText()));
            
            if(BangDiemDao.updateBangDiem(bangDiem)){
                MessageDialogHelper.showMessageDialog(this, "Cập nhật thông tin điểm thành công", "Thông báo");
                loadDataToTable();
            } else {
                MessageDialogHelper.showErrorDialog(this, "Cập nhật thông điểm không thành công", "Lỗi");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton_CapNhatActionPerformed

    private void jButton_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_XoaActionPerformed
        StringBuilder sb = new StringBuilder();
        DataValidator.validatorEmpty(jTextField_MaSinhVien, sb, "Mã sinh viên không được trống");
        if(sb.length() > 0){
            MessageDialogHelper.showErrorDialog(this, sb.toString(), "Lỗi");
            return ;
        }
        if(MessageDialogHelper.showConfirmDialog(this, "Bạn có muốn xóa thông tin điểm sinh viên", "Thông báo") == JOptionPane.NO_OPTION){
            return;
        }
        try {
            if(BangDiemDao.deleteBangDiem(jTextField_MaSinhVien.getText())){
                MessageDialogHelper.showMessageDialog(this, "Xóa thông tin điểm thành công", "Thông báo");
                jButton_NhapMoiActionPerformed(evt);
                loadDataToTable();
            } else {
                MessageDialogHelper.showErrorDialog(this, "Xóa thông điểm không thành công", "Lỗi");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton_XoaActionPerformed

    private void jTextField_MaSinhVienFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_MaSinhVienFocusLost
        try {
            SinhVien sv = SinhVienDao.findByIdStudent(jTextField_MaSinhVien.getText());
            if (sv != null) {
                jTextField_HoTen.setText(sv.getHoTen());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jTextField_MaSinhVienFocusLost

    private void jTextField_TiengAnhFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_TiengAnhFocusLost
        if(jTextField_TiengAnh.getText().equals("") || jTextField_TinHoc.getText().equals("") || jTextField_GDTC.getText().equals("")){
            return ;
        }
        float ta = Float.parseFloat(jTextField_TiengAnh.getText());
        float th = Float.parseFloat(jTextField_TinHoc.getText());
        float tc = Float.parseFloat(jTextField_GDTC.getText());
        
        float tbinh = (ta+th+tc)/3;
        
        String st = String.format("%.2f",tbinh);
        jLabel_TrungBinh.setText(st);
    }//GEN-LAST:event_jTextField_TiengAnhFocusLost

    private void jTextField_TinHocFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_TinHocFocusLost
         if(jTextField_TiengAnh.getText().equals("") || jTextField_TinHoc.getText().equals("") || jTextField_GDTC.getText().equals("")){
            return ;
        }
        float ta = Float.parseFloat(jTextField_TiengAnh.getText());
        float th = Float.parseFloat(jTextField_TinHoc.getText());
        float tc = Float.parseFloat(jTextField_GDTC.getText());
        
        float tbinh = (ta+th+tc)/3;
        
        String st = String.format("%.2f",tbinh);
        jLabel_TrungBinh.setText(st);
    }//GEN-LAST:event_jTextField_TinHocFocusLost

    private void jButton_LocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LocActionPerformed
        try {
            if(jTextField_SoLuong.getText().equals("")){
                loadDataToTable();
            }
            int soLuong = Integer.parseInt(jTextField_SoLuong.getText());
            List<BangDiem> list = BangDiemDao.findTopBangDiem(soLuong);
            if(soLuong>list.size()){
                MessageDialogHelper.showMessageDialog(this, "Số lượng cần lọc lớn hơn số lượng sinh viên", "Thông báo");
                return;
            }
            tblModel.setRowCount(0);
            for(BangDiem bangDiem : list){
                float tb = (bangDiem.getTiengAnh()+bangDiem.getTinHoc()+bangDiem.getGDTC())/3;
                String st = String.format("%.2f", tb);
                SinhVien sv = SinhVienDao.findByIdStudent(bangDiem.getMaSinhVien());
                tblModel.addRow(new Object[]{
                   bangDiem.getMaSinhVien(),sv.getHoTen(),bangDiem.getTiengAnh(),bangDiem.getTinHoc(),bangDiem.getGDTC(),st
                });
            }
            tblModel.fireTableDataChanged();
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_jButton_LocActionPerformed

    private void jTable_QLDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_QLDMouseClicked
        // TODO add your handling code here:
        int row = jTable_QLD.getSelectedRow();
        if(row >= 0){
            String maSinhVien = (String) jTable_QLD.getValueAt(row, 0);
            BangDiem bangDiem = BangDiemDao.findById(maSinhVien);
            SinhVien sv = SinhVienDao.findByIdStudent(maSinhVien);
            jTextField_MaSinhVien.setText(bangDiem.getMaSinhVien());
            jTextField_HoTen.setText(sv.getHoTen());
            jTextField_TiengAnh.setText(bangDiem.getTiengAnh()+"");
            jTextField_TinHoc.setText(bangDiem.getTinHoc()+"");
            jTextField_GDTC.setText(bangDiem.getGDTC()+"");
        }
    }//GEN-LAST:event_jTable_QLDMouseClicked
    
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_CapNhat;
    private javax.swing.JButton jButton_Loc;
    private javax.swing.JButton jButton_Luu;
    private javax.swing.JButton jButton_NhapMoi;
    private javax.swing.JButton jButton_TimKiem;
    private javax.swing.JButton jButton_Xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_TrungBinh;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable_QLD;
    private javax.swing.JTextField jTextField_GDTC;
    private javax.swing.JTextField jTextField_HoTen;
    private javax.swing.JTextField jTextField_MaSinhVien;
    private javax.swing.JTextField jTextField_MaSinhVien_Search;
    private javax.swing.JTextField jTextField_SoLuong;
    private javax.swing.JTextField jTextField_TiengAnh;
    private javax.swing.JTextField jTextField_TinHoc;
    // End of variables declaration//GEN-END:variables
}
