/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import dao.SinhVienDao;
import helper.DataValidator;
import helper.ImageHelper;
import helper.MessageDialogHelper;
import java.awt.Component;
import java.awt.Image;
import java.io.File;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.table.DefaultTableModel;
import model.SinhVien;

/**
 *
 * @author OS
 */
public class StudentManagementPanel extends javax.swing.JPanel {
    private DefaultTableModel tableModel;
    private MainForm parentForm;
    private byte[] personalImage;
    /**
     * Creates new form StudentManagementPanel
     */
    public StudentManagementPanel() {
        initComponents();
        initTable();
        loadDataToTable();
    }
    private void initTable(){
        tableModel = new DefaultTableModel();
        String[] row = new String[]{"Mã sinh viên", "Họ tên","Email","Số điện thoại","Giới tính","Địa chỉ"};
        tableModel.setColumnIdentifiers(row);
        jTable_QLSV.setModel(tableModel);
    }
    private void loadDataToTable(){
        try {
            SinhVienDao dao = new SinhVienDao();
            List<SinhVien> list = dao.findAll();
            tableModel.setRowCount(0);
            for(SinhVien sv : list){
                tableModel.addRow(new Object[]{
                    sv.getMaSinhVien(),sv.getHoTen(),sv.getEmail(),sv.getSoDienThoai(),
                    sv.getGioiTinh()==1 ?"Nam":"Nữ",sv.getDiaChi()
                });
            }
            tableModel.fireTableDataChanged();
        } catch (Exception e) {
        }
    }
    
    public int findRowIndexById(String maSinhVien){
        for(int row = 0; row < jTable_QLSV.getRowCount(); row++){
            String maSinhVienInTable = (String) jTable_QLSV.getValueAt(row, 0);
            if(maSinhVien.equals(maSinhVienInTable)){
                return row;
            }
        }
        return -1;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_GioiTinh = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_MaSinhVien = new javax.swing.JTextField();
        jTextField_HoTen = new javax.swing.JTextField();
        jTextField_Email = new javax.swing.JTextField();
        jTextField_SoDienThoai = new javax.swing.JTextField();
        jRadioButton_Nam = new javax.swing.JRadioButton();
        jRadioButton_Nu = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_DiaChi = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel_Hinh = new javax.swing.JLabel();
        jButton_MoHinh = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jButton_Luu = new javax.swing.JButton();
        jButton_TaoMoi = new javax.swing.JButton();
        jButton_Xoa = new javax.swing.JButton();
        jButton_CapNhat = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_QLSV = new javax.swing.JTable();
        jButton_TimKiem = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("Quản lý sinh viên");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel2.setText("Mã sinh viên :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel3.setText("Họ tên :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel4.setText("Email :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel5.setText("Số điện thoại :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel6.setText("Giới tính :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel7.setText("Địa chỉ :");

        jTextField_MaSinhVien.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jTextField_HoTen.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jTextField_Email.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jTextField_SoDienThoai.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        buttonGroup_GioiTinh.add(jRadioButton_Nam);
        jRadioButton_Nam.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jRadioButton_Nam.setText("Nam");
        jRadioButton_Nam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_NamActionPerformed(evt);
            }
        });

        buttonGroup_GioiTinh.add(jRadioButton_Nu);
        jRadioButton_Nu.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jRadioButton_Nu.setText("Nữ");

        jTextArea_DiaChi.setColumns(20);
        jTextArea_DiaChi.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jTextArea_DiaChi.setRows(5);
        jScrollPane1.setViewportView(jTextArea_DiaChi);

        jLabel_Hinh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Hinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icon/student.png"))); // NOI18N

        jButton_MoHinh.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jButton_MoHinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icon/openImage.png"))); // NOI18N
        jButton_MoHinh.setText("Mở hình");
        jButton_MoHinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_MoHinhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel_Hinh, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_MoHinh)
                .addGap(49, 49, 49))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Hinh, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_MoHinh)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton_Luu.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jButton_Luu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icon/save.png"))); // NOI18N
        jButton_Luu.setText("Lưu");
        jButton_Luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LuuActionPerformed(evt);
            }
        });

        jButton_TaoMoi.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jButton_TaoMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icon/new.png"))); // NOI18N
        jButton_TaoMoi.setText("Tạo mới");
        jButton_TaoMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TaoMoiActionPerformed(evt);
            }
        });

        jButton_Xoa.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jButton_Xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icon/delete.png"))); // NOI18N
        jButton_Xoa.setText("Xóa");
        jButton_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_XoaActionPerformed(evt);
            }
        });

        jButton_CapNhat.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jButton_CapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icon/update.png"))); // NOI18N
        jButton_CapNhat.setText("Cập nhật");
        jButton_CapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CapNhatActionPerformed(evt);
            }
        });

        jTable_QLSV.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jTable_QLSV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_QLSV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_QLSVMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_QLSV);

        jButton_TimKiem.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jButton_TimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icon/search.png"))); // NOI18N
        jButton_TimKiem.setText("Tìm kiếm");
        jButton_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jButton_TaoMoi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_TimKiem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_Luu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_CapNhat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_Xoa)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButton_Nam)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButton_Nu)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jTextField_Email)
                                    .addComponent(jTextField_HoTen)
                                    .addComponent(jTextField_MaSinhVien, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField_SoDienThoai)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE))
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField_MaSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField_HoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jTextField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jTextField_SoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jRadioButton_Nam)
                                .addComponent(jRadioButton_Nu)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_TaoMoi)
                    .addComponent(jButton_Luu)
                    .addComponent(jButton_CapNhat)
                    .addComponent(jButton_Xoa)
                    .addComponent(jButton_TimKiem))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton_NamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_NamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_NamActionPerformed

    private void jButton_TaoMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TaoMoiActionPerformed
        // TODO add your handling code here:
        jTextField_MaSinhVien.setText("");
        jTextField_HoTen.setText("");
        jTextField_Email.setText("");
        jTextField_SoDienThoai.setText("");
        jTextArea_DiaChi.setText("");
        buttonGroup_GioiTinh.clearSelection();
        personalImage = null;
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/mycompany/icon/student.png"));
        jLabel_Hinh.setIcon(icon);
    }//GEN-LAST:event_jButton_TaoMoiActionPerformed

    private void jButton_LuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LuuActionPerformed
        StringBuilder sb = new StringBuilder();
        DataValidator.validatorEmpty(jTextField_MaSinhVien, sb, "Mã sinh viên không được trống");
        DataValidator.validatorEmpty(jTextField_HoTen, sb, "Tên sinh viên không được để trống");
        
        if(sb.length() > 0){
            MessageDialogHelper.showErrorDialog(this, sb.toString(), "Lỗi");
            return ;
        }
        try {
            SinhVien sv = new SinhVien();
            sv.setMaSinhVien(jTextField_MaSinhVien.getText());
            sv.setHoTen(jTextField_HoTen.getText());
            sv.setEmail(jTextField_Email.getText());
            sv.setSoDienThoai(jTextField_SoDienThoai.getText());
            sv.setGioiTinh(jRadioButton_Nam.isSelected() ? 1 : 0);
            sv.setDiaChi(jTextArea_DiaChi.getText());
            sv.setHinh(personalImage);
            if (SinhVienDao.insertStudent(sv)) {
                MessageDialogHelper.showMessageDialog(this, "Thêm mới sinh viên thành công", "Thông báo");
                loadDataToTable();
            } else {
                MessageDialogHelper.showErrorDialog(this, "Sinh viên không được lưu do có lỗi", "Cảnh báo");
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(this, e.getMessage(), "Lỗi");
        }
        
    }//GEN-LAST:event_jButton_LuuActionPerformed

    private void jButton_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TimKiemActionPerformed
        StringBuilder sb = new StringBuilder();
        DataValidator.validatorEmpty(jTextField_MaSinhVien, sb, "Mã sinh viên không được trống");
        
        if(sb.length() > 0){
            MessageDialogHelper.showErrorDialog(this, sb.toString(), "Lỗi");
            return ;
        }
        try {
            SinhVien sv = SinhVienDao.findByIdStudent(jTextField_MaSinhVien.getText());
            if(sv == null){
                MessageDialogHelper.showMessageDialog(this, "Không tìm thấy sinh viên", "Thông báo");
            } else {
                jTextField_MaSinhVien.setText(sv.getMaSinhVien());
                jTextField_HoTen.setText(sv.getHoTen());
                jTextField_Email.setText(sv.getEmail());
                jTextField_SoDienThoai.setText(sv.getSoDienThoai());
                jRadioButton_Nam.setSelected(sv.getGioiTinh()==1);
                jRadioButton_Nu.setSelected(sv.getGioiTinh()==0);
                jTextArea_DiaChi.setText(sv.getDiaChi());
    //            ------------------Hình--------------------
    
    //Chọn hàng trong bảng: 
                int rowIndex = findRowIndexById(jTextField_MaSinhVien.getText());
                if(rowIndex>=0){
                    jTable_QLSV.setRowSelectionInterval(rowIndex, rowIndex);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(this, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_jButton_TimKiemActionPerformed

    private void jButton_CapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CapNhatActionPerformed
        StringBuilder sb = new StringBuilder();
        DataValidator.validatorEmpty(jTextField_MaSinhVien, sb, "Mã sinh viên không được trống");
        DataValidator.validatorEmpty(jTextField_HoTen, sb, "Tên sinh viên không được để trống");
        
        if(sb.length() > 0){
            MessageDialogHelper.showErrorDialog(this, sb.toString(), "Lỗi");
            return ;
        }
        try {
            SinhVien sv = new SinhVien();
            sv.setMaSinhVien(jTextField_MaSinhVien.getText());
            sv.setHoTen(jTextField_HoTen.getText());
            sv.setEmail(jTextField_Email.getText());
            sv.setSoDienThoai(jTextField_SoDienThoai.getText());
            sv.setGioiTinh(jRadioButton_Nam.isSelected() ? 1 : 0);
            sv.setDiaChi(jTextArea_DiaChi.getText());
            sv.setHinh(personalImage);
            if (SinhVienDao.updateStudent(sv)) {
                MessageDialogHelper.showMessageDialog(this, "Cập nhật sinh viên thành công", "Thông báo");
                loadDataToTable();
            } else {
                MessageDialogHelper.showErrorDialog(this, "Sinh viên không được cập nhật do có lỗi", "Cảnh báo");
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(this, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_jButton_CapNhatActionPerformed

    private void jButton_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_XoaActionPerformed
        StringBuilder sb = new StringBuilder();
        DataValidator.validatorEmpty(jTextField_MaSinhVien, sb, "Mã sinh viên không được trống");
        
        if(sb.length() > 0){
            MessageDialogHelper.showErrorDialog(this, sb.toString(), "Lỗi");
            return ;
        }
        if(MessageDialogHelper.showConfirmDialog(this, "Bạn có muốn xóa sinh viên này ?", "Thông báo") == JOptionPane.NO_OPTION){
            return ;
        }
        try {
            if(SinhVienDao.deleteStudent(jTextField_MaSinhVien.getText())){
                MessageDialogHelper.showMessageDialog(this, "Xóa sinh viên thành công", "Thông báo");
                jButton_TaoMoiActionPerformed(evt);
                loadDataToTable();
            } else {
                MessageDialogHelper.showErrorDialog(this, "Sinh viên không xóa được do có lỗi", "Thông báo");
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(this, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_jButton_XoaActionPerformed

    private void jTable_QLSVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_QLSVMouseClicked
        try {
            int row = jTable_QLSV.getSelectedRow();
            if(row>=0){
                String maSinhVien = (String) jTable_QLSV.getValueAt(row, 0);
                SinhVien sv = SinhVienDao.findByIdStudent(maSinhVien);
                if(sv!=null){
                    jTextField_MaSinhVien.setText(sv.getMaSinhVien());
                    jTextField_HoTen.setText(sv.getHoTen());
                    jTextField_Email.setText(sv.getEmail());
                    jTextField_SoDienThoai.setText(sv.getSoDienThoai());
                    jRadioButton_Nam.setSelected(sv.getGioiTinh()==1);
                    jRadioButton_Nu.setSelected(sv.getGioiTinh()==0);
                    jTextArea_DiaChi.setText(sv.getDiaChi());
                    if(sv.getHinh()!=null){
                        Image img = ImageHelper.createImageFromByArray(sv.getHinh(), "png");
                        jLabel_Hinh.setIcon(new ImageIcon(img));
                        personalImage = sv.getHinh();
                    } else {
                        personalImage = sv.getHinh();
                        ImageIcon icon = new ImageIcon(getClass().getResource("/com/mycompany/icon/student.png"));
                        jLabel_Hinh.setIcon(icon);
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(this, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_jTable_QLSVMouseClicked

    private void jButton_MoHinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_MoHinhActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileFilter(new FileFilter() {
            @Override
            public boolean accept(File f) {
                if(f.isDirectory()){
                    return true;
                } else {
                    return f.getName().toLowerCase().endsWith(".png");
                }
            }

            @Override
            public String getDescription() {
                return "Image file (*.png)";
            }
        });
        if(chooser.showOpenDialog(parentForm) == JFileChooser.CANCEL_OPTION){
            return;
        }
        File file = chooser.getSelectedFile();
        try {
            ImageIcon icon = new ImageIcon(file.getPath());
            Image img = ImageHelper.resize(icon.getImage(), 140, 140);
            ImageIcon resizedIcon = new ImageIcon(img);
            jLabel_Hinh.setIcon(icon);
            personalImage = ImageHelper.toByArray(img, "png");
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showMessageDialog(parentForm, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_jButton_MoHinhActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_GioiTinh;
    private javax.swing.JButton jButton_CapNhat;
    private javax.swing.JButton jButton_Luu;
    private javax.swing.JButton jButton_MoHinh;
    private javax.swing.JButton jButton_TaoMoi;
    private javax.swing.JButton jButton_TimKiem;
    private javax.swing.JButton jButton_Xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_Hinh;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton_Nam;
    private javax.swing.JRadioButton jRadioButton_Nu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable_QLSV;
    private javax.swing.JTextArea jTextArea_DiaChi;
    private javax.swing.JTextField jTextField_Email;
    private javax.swing.JTextField jTextField_HoTen;
    private javax.swing.JTextField jTextField_MaSinhVien;
    private javax.swing.JTextField jTextField_SoDienThoai;
    // End of variables declaration//GEN-END:variables
}
